### ISSUE TITLE
Values Updation in SPIDER_MAN

### ISSUE THREAD

**Issue by ankitparida** [ookAI/PyCon2019_devsprint#7]
the upper and lower values needs to be updated in SPIDER_MAN

**Comment by ankitparida** [comment]
@krishnakatyal

**Comment by Gorav123** [comment]
@ankitparida the values are already updated.

**Comment by ankitparida** [comment]
![Screenshot (15)_LI](https://user-images.githubusercontent.com/30798966/66734108-7ef8c280-ee7f-11e9-86cc-ff616e8648ed.jpg)
