### ISSUE TITLE
junk to be removed in batman

### ISSUE THREAD

**Issue by shubra1999** [ookAI/PyCon2019_devsprint#8]
iron_man issue missing part
 blocks need to be removed.
![Screenshot (1)](https://user-images.githubusercontent.com/29538489/66734000-26c1c080-ee7f-11e9-8ff9-d2859fdc6c18.png)

**Comment by shubra1999** [comment]
@krishnakatyal

**Comment by iamrrc007** [comment]
@shubra1999 Do it yourself lazy
