### ISSUE TITLE
Remove numbers from sentence

### ISSUE THREAD

**Issue by iamrrc007** [ookAI/PyCon2019_devsprint#9]
Remove numbers "P5lea9se ad5d mo55re feat4ur6es"
![Untitled](https://user-images.githubusercontent.com/56531792/66734157-a64f8f80-ee7f-11e9-8a30-a5c77e1b5699.png)

**Comment by iamrrc007** [comment]
The sentence is having numbers. Kindly remove...

**Comment by iamrrc007** [comment]
@krishnakatyal

**Comment by shubra1999** [comment]
@iamrrc007  i have removed the issue
